# Generated by Django 4.0.3 on 2022-03-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=20)),
                ('apellido', models.TextField(max_length=20)),
                ('dni', models.IntegerField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
    ]
