# Generated by Django 4.0.3 on 2022-03-30 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_familia_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='apellido',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='familia',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
