# Generated by Django 4.0.3 on 2022-03-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_familia_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='apellido',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='familia',
            name='nombre',
            field=models.TextField(max_length=20),
        ),
    ]
